// revenue-builder.js -- Round 20. Turns a product SPEC into a gated, release-
// ready product using headless Claude, with no human step in the loop:
//   budget check -> Claude writes the product (cwd = its own dir) -> the
//   ORCHESTRATOR gates it (product-gate.js: secrets, manifest, policy, own
//   tests, spec-owned acceptance cases, all offline) -> failures go back to
//   the same Claude session -> up to maxRounds -> release bundle + commit.
// Products live in a SEPARATE repo (AgentVault-products), never in the city
// repo. Publishing needs marketplace credentials the owner must provide once
// (publishStatus() says exactly what is missing); everything before that is
// autonomous.
//
// Spec: { slug, title, entry, description, pricing, disclaimer, allowedHosts[],
//         allowedDeps[], requirements (prompt text), acceptance:[{name,input|inputFile,expect}],
//         fixturesDir? }

const avPaths = require('../lib/paths.js');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { spawnSync } = require('child_process');
const worker = require('./claude-worker.js');
const budget = require('./builder-budget.js');
const gate = require('./product-gate.js');

const DEFAULT_PRODUCTS_ROOT = avPaths.PRODUCTS_REPO;

function git(dir, args) { return spawnSync('git', ['-C', dir, ...args], { encoding: 'utf8' }); }

function ensureRepo(root) {
  fs.mkdirSync(root, { recursive: true });
  if (!fs.existsSync(path.join(root, '.git'))) {
    git(root, ['init', '-q']);
    git(root, ['config', 'user.email', 'builder@agentvault.local']);
    git(root, ['config', 'user.name', 'agentvault-builder']);
  }
}

function resolveAcceptance(spec, specDir) {
  return spec.acceptance.map((c) => ({ ...c, input: c.inputFile ? fs.readFileSync(path.join(specDir || '.', c.inputFile), 'utf8') : c.input }));
}

function buildPrompt(spec, cases) {
  return [
    `You are building a small, sellable software product: "${spec.title}".`,
    'Work ONLY inside the current directory. You can read/write/edit files but you cannot run commands or browse; the orchestrator runs your tests and an independent acceptance check afterwards and will send you the failures.',
    '', '## What to build', spec.requirements,
    '', '## Required layout',
    '- package.json (no install/postinstall scripts; dependencies exact-pinned and ONLY from: ' + (spec.allowedDeps.length ? spec.allowedDeps.join(', ') : 'none -- use Node built-ins') + ')',
    '- LICENSE (MIT) and README.md (what it does, input/output, honest limitations, the disclaimer below)',
    `- src/core.js exporting the pure function \`${spec.entry}\` (no network, no I/O inside it)`,
    '- tests/*.test.js using node:test that exercise src/core.js offline',
    '- any network code must only contact these hosts: ' + spec.allowedHosts.join(', '),
    '- do NOT use child_process, eval, or new Function. Never include credentials or keys.',
    '', '## Disclaimer to include verbatim in README.md', spec.disclaimer,
    '', '## Acceptance cases your `' + spec.entry + '` must satisfy (inputs abbreviated to 400 chars; full inputs are used by the checker)',
    ...cases.map((c) => `- ${c.name}: input=${JSON.stringify(String(typeof c.input === 'string' ? c.input : JSON.stringify(c.input)).slice(0, 400))} expect(subset)=${JSON.stringify(c.expect)}${c.spread ? ' -- NOTE: the input array is spread into separate arguments: ' + (c.entry || spec.entry) + '(...input)' : ''}`),
  ].join('\n');
}

function feedbackPrompt(failures) {
  return ['The orchestrator gated your product and it FAILED. Fix every item below by editing files, then stop.', ...failures.map((f) => `- ${f}`)].join('\n');
}

function writeReleaseBundle(dir, spec) {
  const body = [`# ${spec.title}`, '', spec.description, '', `**Pricing:** ${spec.pricing}`, '', `**Disclaimer:** ${spec.disclaimer}`, '', '_Generated by the AgentVault revenue builder. The listing is publish-ready once marketplace credentials exist._', ''].join('\n');
  fs.writeFileSync(path.join(dir, 'RELEASE.md'), body);
}

async function buildProduct(spec, { productsRoot = DEFAULT_PRODUCTS_ROOT, specDir, claudeFn = worker.dispatchClaudeAsync, maxRounds = 4, now = Date.now(), literals, model = process.env.BUILDER_MODEL || 'sonnet', effort = process.env.BUILDER_EFFORT || 'high' } = {}) {
  const decision = budget.canBuild({ now });
  if (!decision.ok) return { status: 'deferred', reason: decision.reason, until: decision.until || null };
  ensureRepo(productsRoot);
  const dir = path.join(productsRoot, spec.slug);
  fs.mkdirSync(dir, { recursive: true });
  const cases = resolveAcceptance(spec, specDir);
  const gateSpec = { ...spec, acceptance: cases };
  let sessionId = crypto.randomUUID();
  let prompt = buildPrompt(spec, cases);
  let last = null, rounds = 0;
  for (let round = 1; round <= maxRounds; round++) {
    rounds = round;
    const run = await claudeFn(prompt, { cwd: dir, model, effort, ...(round === 1 ? { sessionId } : { resume: sessionId }) });
    budget.recordRun(run, { now, countAsBuild: round === 1 });
    if (run.sessionId) sessionId = run.sessionId;
    if (run.spawnError || run.timedOut) return { status: 'error', reason: run.spawnError || 'builder timed out', rounds };
    const stillOk = budget.canBuild({ now: Date.now(), cfg: { ...budget.readConfig(), dailyBuilds: Infinity } });
    if (!stillOk.ok && run.isError) return { status: 'paused', reason: stillOk.reason, rounds };
    last = gate.runGate(dir, gateSpec, { literals });
    if (last.ok) {
      writeReleaseBundle(dir, spec);
      git(productsRoot, ['add', '--', spec.slug]);
      git(productsRoot, ['commit', '-q', '-m', `Add ${spec.slug} (gate passed, round ${round})`]);
      return { status: 'built', rounds, dir };
    }
    prompt = feedbackPrompt(last.failures);
  }
  return { status: 'gate-failed', rounds, failures: last ? last.failures : [] };
}

// What still needs the owner, stated exactly, so autonomy after that is real.
function publishStatus({ hasSecret = require('../platform/secrets-broker.js').hasSecret } = {}) {
  const needs = [];
  if (!hasSecret('APIFY_TOKEN')) needs.push('APIFY_TOKEN (Apify account API token, to publish Actors)');
  if (!hasSecret('STRIPE_LIVE_RESTRICTED_KEY')) needs.push('STRIPE_LIVE_RESTRICTED_KEY (optional: direct-sale Payment Links / cross-check)');
  return { ready: needs.length === 0, needs };
}

module.exports = { buildProduct, buildPrompt, feedbackPrompt, resolveAcceptance, publishStatus, ensureRepo, DEFAULT_PRODUCTS_ROOT };

if (require.main === module) {
  const [cmd, specPath] = process.argv.slice(2);
  if (cmd !== 'build' || !specPath) { console.error('usage: node revenue-builder.js build <spec.json>'); process.exit(2); }
  const abs = path.resolve(specPath);
  const spec = JSON.parse(fs.readFileSync(abs, 'utf8'));
  buildProduct(spec, { specDir: path.dirname(abs) })
    .then((r) => { console.log(JSON.stringify(r, null, 2)); console.log(JSON.stringify(publishStatus())); process.exit(r.status === 'built' ? 0 : 1); })
    .catch((e) => { console.error('builder failed:', e.message); process.exit(1); });
}
